<?php

namespace App\Http\Requests\Api\Cart;

use App\Enums\ProductStructure;
use App\Http\Requests\Api\ApiFormRequest;
use App\Models\Product;
use App\Rules\AddToCartRule;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Contracts\Validation\Rule;

class SyncCartRequest extends ApiFormRequest
{
    protected $stopOnFirstFailure = true;
    protected $products;
    protected int $min_purchases_per_user = 1;
    protected int $max_purchases_per_user = 1;
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {

        return [
            'items.*.id'=>[
                'required',
                'exists:App\Models\Product,id',
            ],
            'items.*.quantity'=> [
                'required',
                'integer',
                function ($attribute, $value, $fail) {
                    $product = $this->products[$this->get('items')[substr($attribute, 6, -9)]['id']];
                    return $product->min_purchases_per_user ?? 1;
                },
                function ($attribute, $value, $fail) {
                    $product = $this->products[$this->get('items')[substr($attribute, 6, -9)]['id']];
                    return $product->max_purchases_per_user ?? 1;
                },
            ],
            'products'=>'nullable',
        ];
    }

    protected function prepareForValidation()
    {
        parent::prepareForValidation(); // TODO: Change the autogenerated stub
        if($this->has('items')){
            $this->products = $this->convertItemsToProducts($this->get('items'));
        }
        if(isset($this->products)) {
            $this->merge([
                'products' => $this->products
            ]);
        }
    }

    protected function passedValidation()
    {
//        $this->merge([
//            'structure' => $this->product->structure,
//            'is_virtual' => $this->product->is_virtual
//        ]);
    }

    public function messages()
    {
        return [
          'quantity.max'=>'تعداد درخواستی شما برای خرید بیشتر از حد مجاز است!',
          'quantity.min'=>'تعداد درخواستی شما برای خرید کمتر از حد مجاز است!',
        ];
    }

    private function convertItemsToProducts($items){
        $products = [];
        foreach ($items as $item){
            if(isset($item['id']))
                $products[(string)$item['id']] = Product::query()->find($item['id']);
                $products[(string)$item['id']]['cart_quantity'] = Product::query()->find($item['id']);
        }
        return $products;
    }
}
