// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useCreator: typeof import('@/Composables/useCreator.js')['default']
  const useProduct: typeof import('@/Composables/useProduct.js')['default']
  const useStock: typeof import('@/Composables/useStock.js')['default']
}
