// Generated by 'unplugin-auto-import'
export {}
declare global {
  const useCreator: typeof import('@/Composables/useCreator.js')['default']
  const useProduct: typeof import('@/Composables/useProduct.js')['default']
  const useStock: typeof import('@/Composables/useStock.js')['default']
  const useCollection: typeof import('@/Composables/useCollection.js')['default']
  const useOrder: typeof import('@/Composables/useOrder.js')['default']
  const useModal: typeof import('@/Composables/useModal.js')['default']
  const useForm: typeof import('@/Composables/useForm.js')['default']
}
