<?php

namespace App\Http\Requests\Api\Checkout;

use App\Http\Requests\Api\ApiFormRequest;
use App\Models\Cart;
use App\Services\CartService;
use Illuminate\Validation\ValidationException;

class PayRequest extends ApiFormRequest
{
    protected $stopOnFirstFailure = true;

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'first_name'=> 'required',
            'last_name'=> 'required',
            'state_id'=> 'required',
            'city_id'=> 'required',
            'postal_code'=> 'nullable',
            'address'=> 'required',
            'phone'=>'required',
            'mobile'=> 'required',
        ];
    }

    public function messages()
    {
        return [

        ];
    }

    protected function prepareForValidation()
    {
        parent::prepareForValidation(); // TODO: Change the autogenerated stub
        if((new CartService())->getCart()->doesntExist()){
            throw ValidationException::withMessages(['cart_is_empty' => 'سبد خرید شما خالی است!']);
        }
    }
}
