<?php declare(strict_types=1);

namespace App\Enums;

use BenSampo\Enum\Contracts\LocalizedEnum;
use BenSampo\Enum\Enum;

final class ProductStructure extends Enum  implements LocalizedEnum
{
    const BOOK = 1;
    const STATIONERY = 2;
    const CRAFT = 3;
    const PRODUCT = 4;

    protected static function getConstants(): array
    {
        $c = null;
        foreach (parent::getConstants() as $value=> $constant){
            $c[strtolower($value)] = $constant;
        }
        return $c; // TODO: Change the autogenerated stub
    }
}
